version: "3"

services:
  strapi:
    build: 
      context: ./
      args:
        BASE_VERSION: latest
        STRAPI_VERSION: 4
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}


    networks:
      - caddy
    volumes:
      - ./app:/srv/app
    labels:
      caddy: content.seanaye.ca
      caddy.reverse_proxy: "{{upstreams 1337}}"

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - caddy
    volumes:
      - strapidata:/var/lib/postgresql/data/

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  strapidata: {}
  caddy_data: {}
